# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:android)

platform :android do
  desc "Test build"
  lane :test do
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )
  end

  desc "Deploy to the Google Play"
  lane :deploy do
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )
    upload_to_play_store(track: 'beta', release_status: 'draft')
  end
end
