# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - app/**

jobs:
  deploy-play-store:
    name: Deploy to Google Play Store
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Configure keystore
        run: |
          echo $KEYSTORE_KEY_JKS | base64 -d > app/keystore.jks
          echo "storeFile=keystore.jks" >> keystore.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> keystore.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> keystore.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> keystore.properties
        env:
          KEYSTORE_KEY_JKS: ${{ secrets.KEYSTORE_KEY_JKS }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}

      - name: Create Google Play config file
        run: |
          echo "$PLAY_CONFIG_JSON" | base64 -d > play_config.json
        env:
          PLAY_CONFIG_JSON: ${{ secrets.PLAY_CONFIG_JSON }}

      - name: Deploy to Google Play
        uses: maierj/fastlane-action@v2.3.0
        with:
          lane: deploy

      - name: Release to GitHub
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "beta"
          prerelease: true
          title: "Beta Release"
          files: |
            LICENSE
            CHANGELOG
            app/build/outputs/bundle/release/app-release.aab
